spring:
  profiles:
    active: dev
  application:
    name: user-service
  thymeleaf:
    cache: false
##jdbc
  datasource:
    url: jdbc:mysql://localhost:3306/green?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: green
    password: Green123!
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    database : MYSQL
    show-sql: true
server:
  port: 9901

##mybatis
mybatis:
 #mybatis.mapper-recyclerInfos=classpath:mapper/*.xml
  typeAliasesPackage: com.jingling.basic.po
  mapperLocations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
#http://120.79.201.63:8000/eureka/

#微信相关配置


#公网ip相关
address:
  server:
    ip: http://www.xxx.cn/
    mail:
      validate: user/validate/